services:
    sonata.admin.post:
        class: AyrshireMinis\ContactBundle\Admin\ContactAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Leads", label: "Contacts" }
        arguments:
            - ~
            - AyrshireMinis\ContactBundle\Entity\Contact
            - ~
        calls:
            - [ setTranslationDomain, [AyrshireMinisContactBundle]]