imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        cssembed:
          jar: %kernel.root_dir%/Resources/java/cssembed-0.4.5.jar
        yui_js:
          jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
        lessphp:
          apply_to: "\.less$"
          formatter: "compressed"
        #less:
            #node: /usr/local/bin/node
            #node_paths: [/usr/local/lib/node_modules]
            #apply_to: "\.less$"
    assets:
        bootstrap_css:
          inputs:
              # This is a custom build file which works together with bootswatch.
              # Note that all files you specify here are processed one after each other,
              # so you can't simply add twitter's bootstrap.less and your local variables.less here.
              # You can choose whatever directory you wish, and name it whatever you wish.
            - %kernel.root_dir%/../src/AyrshireMinis/CommonBundle/Resources/less/build.less
          filters:
              - lessphp
              - cssrewrite
            # This is the output file which you'll have to include using asset('css/bootstrap.css') in your template.
            # You can generate the CSS file by using the assetic:dump sf2 command (php app/console assetic:dump)
          output: css/bootstrap.css
        #jquery_js:
         #   inputs:
          #      - '%kernel.root_dir%/../components/jquery/jquery.min.js'
           # filters: [?yui_js]
        #bootstrap_js:
         #   inputs:
          #      - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/transition.js'
           #     - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/alert.js'
            #    - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/modal.js'
             #   - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/dropdown.js'
              #  - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/scrollspy.js'
               # - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/tab.js'
          #      - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/tooltip.js'
           #     - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/popover.js'
            #    - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/button.js'
             #   - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/collapse.js'
              #  - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/carousel.js'
               # - '%kernel.root_dir%/../vendor/twitter/bootstrap/js/affix.js'
            #filters: [?yui_js]
        #bootstrap_less:
         #   inputs:
          #      - '%kernel.root_dir%/../vendor/twitter/bootstrap/less/bootstrap.less'
          #  filters: [cssembed]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
