imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @AyrshireMinisGalleryBundle/Resources/config/admin.yml }
    - { resource: @AyrshireMinisCommonBundle/Resources/config/admin.yml }
    - { resource: @AyrshireMinisContactBundle/Resources/config/admin.yml }
    - { resource: sonata/block.yml }
    - { resource: sonata/admin.yml }
    - { resource: sonata/user.yml }
    - { resource: doctrine/config.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        cssembed:
          jar: %kernel.root_dir%/Resources/java/cssembed-0.4.5.jar
        yui_js:
          jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
        lessphp:
          apply_to: "\.less$"
          formatter: "compressed"
        #less:
            #node: /usr/local/bin/node
            #node_paths: [/usr/local/lib/node_modules]
            #apply_to: "\.less$"
    assets:
        bootstrap_css:
          inputs:
              # This is a custom build file which works together with bootswatch.
              # Note that all files you specify here are processed one after each other,
              # so you can't simply add twitter's bootstrap.less and your local variables.less here.
              # You can choose whatever directory you wish, and name it whatever you wish.
            - %kernel.root_dir%/../src/AyrshireMinis/CommonBundle/Resources/less/build.less
          filters:
              - lessphp
              - cssrewrite
            # This is the output file which you'll have to include using asset('css/bootstrap.css') in your template.
            # You can generate the CSS file by using the assetic:dump sf2 command (php app/console assetic:dump)
          output: css/bootstrap.css

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Google Analytics
google:
    analytics:
        trackers:
            default:
                name:      AyrshireMinis
                accountId: UA-2769290-1
                domain:    .ayrshireminis.com
                trackPageLoadTime: true


fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)
    service:
        user_manager: sonata.user.orm.user_manager # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)
