ayrshire_minis_common:
    resource: "@AyrshireMinisCommonBundle/Controller/"
    type:     annotation
    prefix:   /

ayrshire_minis_contact:
    resource: "@AyrshireMinisContactBundle/Controller/"
    type:     annotation
    prefix:   /
