ayrshire_minis_gallery:
    resource: "@AyrshireMinisGalleryBundle/Resources/config/routing.yml"
    prefix:   /

ayrshire_minis_common:
    resource: "@AyrshireMinisCommonBundle/Controller/"
    type:     annotation
    prefix:   /

ayrshire_minis_contact:
    resource: "@AyrshireMinisContactBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin