services:
    sonata.gallery.admin.post:
        class: AyrshireMinis\GalleryBundle\Admin\GalleryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Gallery", label: "Image" }
        arguments:
            - null
            - AyrshireMinis\GalleryBundle\Entity\GalleryImage
            - AyrshireMinisGalleryBundle:CRUD
        calls:
            - [ setTranslationDomain, [AyrshireMinisGalleryBundle]]