ayrshireminis_gallery_homepage:
    pattern:  /gallery
    defaults: { _controller: AyrshireMinisGalleryBundle:Default:index }

ayrshireminis_gallery_add:
    pattern:  /gallery/add
    defaults: { _controller: AyrshireMinisGalleryBundle:Default:add }

ayrshireminis_gallery_submit:
    pattern:  /gallery/add/submit
    defaults: { _controller: AyrshireMinisGalleryBundle:Default:add }
