parameters:
#    ayrshire_minis_gallery.example.class: AyrshireMinis\GalleryBundle\Example

services:
#    ayrshire_minis_gallery.example:
#        class: %ayrshire_minis_gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
